### ISSUE TITLE
sparkfun xbee dongles no longer work for firmware upgrades

### ISSUE THREAD

**Issue by williamcodes** [heatseeknyc/firmware#11]
X-CTU now hangs when trying to write a new profile to an xbee.

**Comment by williamcodes** [comment]
I spoke to Eric Flanders, a tech support agent at Digi, and he said the reason is because the sparkfun dongles don't have Ready To Send (RTS) and Data Terminal Ready (DTR) lines for hardware handshaking. Both are necessary to do firmware upgrades. He recommended we buy their interface boards. I spoke to Chad from sales and he recommended we get this one from DigiKey:

http://www.digikey.com/product-detail/en/XBIB-U/XBIB-U-ND/935972

I'm gonna order one and see if it works.

**Comment by hrldcpr** [comment]
That's odd though, was he able to explain why these exact dongles worked a couple months ago?

**Comment by williamcodes** [comment]
You made a good point so I went to SparkFun and asked them for help. Their tech support agent was more helpful. I reinstalled the FTDI driver and it worked for one of the XBees. After talking to him, I tried 3 other XBees and none of them have worked.

**Comment by williamcodes** [comment]
We switched to programming XBees on a linux machine a few weeks ago and things have been working fine since we did that so I'm closing this issue.
