### ISSUE TITLE
install some kind of SQL CLI

### ISSUE THREAD

**Issue by williamcodes** [heatseeknyc/firmware#14]
We need a way to check if hubs have received readings from cells but not relayed them. I'm thinking the sqlite3 binary since their local databases are in sqlite3 and that binary comes with a REPL.

**Comment by hrldcpr** [comment]
This is already added by 4c02498 for future builds, and by [migrate1.sh](https://github.com/heatseeknyc/firmware/blob/2ef297ddb2a28a696c210d75d78c4d1ccc9b7588/temp/migrate1.sh#L2) when updating existing hubs.

**Comment by williamcodes** [comment]
Nice, way to go Harold!
