### ISSUE TITLE
v1.5 hub firmware does not transmit readings to relay

### ISSUE THREAD

**Issue by williamcodes** [heatseeknyc/firmware#15]
I updated 01F1 from pre-v1.2 to the latest this morning at around 8am. That hour, it stopped transmitting readings to the relay server. I'm looking into how to revert it to v1.4 now. Can we get the readings from the intervening hours back? More interestingly, what is wrong with v1.5?

**Comment by williamcodes** [comment]
I did `git reset --hard v1.4` on 01F1. We'll see if that brings it back up.

**Comment by williamcodes** [comment]
Ugh, I'm an idiot, forgot to migrate the database. Let's see if that fixes it.

**Comment by hrldcpr** [comment]
Looks like 01F1 is still running v1.4.

But [2506](http://relay.heatseeknyc.com/hubs/0013a20040d84807) is running v1.5 and transmitting readings, so I'm pretty sure it works as long as you run `tmp/migrate1.sh`, closing this for now.

**Comment by williamcodes** [comment]
yup, good call, it's working for me here in the office too, I tested it as well
