### ISSUE TITLE
suggestion from @cromulus

### ISSUE THREAD

**Issue by williamcodes** [heatseeknyc/firmware#16]
to add to build.sh

```
# tests if self is root
if [ "$(id -u)" = "0" ]; then
   echo "This script must NOT run as root" 1>&2
   exit 1
fi

# tests if the repo was cloned by root
if [ "$(stat -c %U `basename $BASH_SOURCE`)" = "root" ]; then
  echo "this was checked out by root and owned by root. should be pi"
  exit 1
fi
```

this checks to make sure you’re not installing as root and root doesn’t own the files.

**Comment by hrldcpr** [comment]
Checking `whoami` is incorporated into the latest `build.sh` script, and it checks out the git repository itself, so the ownership is guaranteed.
