### ISSUE TITLE
create database as part of build script

### ISSUE THREAD

**Issue by williamcodes** [heatseeknyc/firmware#17]
add this line to build script perhaps?

```
sqlite3 heatseek.db < /home/$HOME/firmware/schema.sql
```

https://github.com/heatseeknyc/firmware/blob/dev/build.sh#L25

In order to make it idempotent though, we should move the migration to a `migrate` folder and have the build script run all those migrations automatically. That way we can run the `build.sh` script from any pi and it will get it to the right place.

**Comment by hrldcpr** [comment]
Closed by d0c7202
