### ISSUE TITLE
turning on the pull-up resistors

### ISSUE THREAD

**Issue by williamcodes** [heatseeknyc/firmware#24]
We need to turn on the pull-up resistors to save power. To do this, set `PR` to `1DEF` in the following places:
- cell.xml
- cell-pro.xml
- the firmware readme

**Comment by williamcodes** [comment]
Going to test this in the office one more time and then deploy the first cell with the updated firmware this afternoon.

**Comment by williamcodes** [comment]
Tested the new programming on a short-range xbee and saw expected results.

**Comment by williamcodes** [comment]
Tested on long-range and saw expected results. This should be good. I'm going to deploy a cell in the Bronx with v1.6.

**Comment by williamcodes** [comment]
The cell in the field seems to be reporting consistently, although there is less variation in the temperature than expected. It seems fixed at 72ºF. There isn't enough data yet though for this to be considered anomalous.

http://relay.heatseeknyc.com/cells/0013a20040b9e36e

**Comment by hrldcpr** [comment]
Huh, those are extremely flat readings, though yeah could be right, hard to say! Gonna double check the PR value and then merge your... PR?! 🙉
