### ISSUE TITLE
Base "Last seen x seconds ago" message off of reading time instead of hub time

### ISSUE THREAD

**Issue by williamcodes** [heatseeknyc/firmware#6]
Currently, when setting up cells, the setup page uses the time the relay server receives signals from the hub in determining what to display for the "Last seen x seconds ago" messaging for cells as well as hubs. This means that cells which may have long since been disconnected could show up as last seen a few seconds ago simply because the hub was seen a few seconds ago. To fix this, we need to base the "Last seen x seconds ago" message for the cells off of the timestamp included in the reading.

**Comment by hrldcpr** [comment]
Moving this to heatseeknyc/relay#8 since it's not related to firmware.
